### PR TITLE
maintenance

### PR DESCRIPTION
**Pull request by TacoTheDank**
- target android pie
- update dependencies
- migrate app to appCompat
- migrate to androidx
- java 1.8 compatibility
- fix some english (longtitude to longitude, etc)
- reformat code

### CODE REVIEW

**Comment by Fr4gorSoftware** [comment]
Thank you for the maintenance work. I have two things that have be changed in your version and one question. If you fix the following things the pull request will be accepted.
- buildToolsVersion '28.0.3' coast problems for a lot of users. Look at this issue #55. Using buildToolsVersion '26.0.2' fixed that problem. Please switch back to version 26.0.2 and check if the gradle version you are using is capable with buildToolsVersion '26.0.2'. The same goes for Java 1.8.
- Why do you have inserted` * <p>` in a lot of classes, is there any reason?
- the option menu should always be shown in history

**Comment by TacoTheDank** [comment]
🤔 That's strange... I'll upload the apks I built with my changes (built after commit 0dae4c1). I'll refer those users to try these builds and see if there's any difference.
[SecScanQR.zip](https://github.com/Fr4gorSoftware/SecScanQR/files/2617596/SecScanQR.zip)

(The <p> insertions were done automatically when I reformatted the code)

**Comment by TacoTheDank** [comment]
I reset branch back to 7f05923, as androidx can only be used with compileSdkVersion 28+

**Comment by Fr4gorSoftware** [comment]
Please fix following error:
- Gradle Version 3.2.0 does not support buildTools 26.0.2 -> The specified Android SDK Build Tools version (26.0.2) is ignored, as it is below the minimum supported version (28.0.2) for Android Gradle Plugin 3.2.0.

**Comment by TacoTheDank** [comment]
ohmygod xd hold on

**Comment by TacoTheDank** [comment]
I'm going to just redo this instead of fixing all the conflicts.

**Pull request closed without merging**
