### PR TITLE
Add zh-rTW translations.

### PR DESCRIPTION
**Pull request by s8321414**
I added zh-rTW translations, please review and merge it :smiley:

### CODE REVIEW

**Comment by Fr4gorSoftware** [comment]
Thank you for the translation.
Some small things have to be changed:

- String arrays: generators and barcode_formats_array should not be translated
- Your name instead of mine should appear in the string: translator

The rest is fine :-)

**Comment by s8321414** [comment]
@Fr4gorSoftware Should I squash my commit into one? Or I can push multiple commits to this PR?

**Comment by s8321414** [comment]
For some reason, I merge all of them into one :smiley:

**Comment by Fr4gorSoftware** [comment]
Now it is fine. Thank you

**Pull request merged**
